#!/bin/bash
CONDA_BASE=$(conda info --base)
conda create -y -n pignet python=3.11
source $CONDA_BASE/etc/profile.d/conda.sh
conda activate pignet
conda install -y numpy
conda install -y pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
conda install -y -c bioconda smina 
conda install -y -c conda-forge biopython
conda install -y -c anaconda scikit-learn
conda install -y -c conda-forge scipy
conda install -y -c conda-forge rdkit
conda install -y -c schrodinger pymol

